!                    *****************
                     SUBROUTINE SEDI3D_EROD
!                    *****************

     &  (CONC,EPAI,FLUER,TOB,DENSI,
     &  MPART,DT,NPOIN2,NCOUCH,TOCE,
     &  HN,HMIN,MIXTE,EPAICO,
     &  CFDEP,WC,HDEP,
     &  NPOIN3,KSPRATIO,AC,RHOS,RHO0,
     &  GRAV,DMOY,CREF,ZREF,CF,ICQ,RUGOF,Z,UETCAR,
     &  SETDEP,EPAINCO ,
     &  KARMAN,PRANDTL,FICT,FLUERC, FLUERNC, NTRAC   , ITRAC,
     &  SEDCO, SEDNCO)

      USE BIEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE

      TYPE(BIEF_OBJ), INTENT(INOUT) :: TOB
      TYPE(BIEF_OBJ), INTENT(IN)    :: HN

      INTEGER,          INTENT(IN)    :: NPOIN2,NCOUCH
      DOUBLE PRECISION, INTENT(IN)    :: CONC(NPOIN2,NCOUCH)
      DOUBLE PRECISION, INTENT(IN)    :: TOCE(NPOIN2,NCOUCH)
      DOUBLE PRECISION, INTENT(INOUT) :: EPAI(NPOIN2,NCOUCH)
      DOUBLE PRECISION, INTENT(IN)    :: EPAICO(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: FLUER(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DENSI(NPOIN2)
      LOGICAL,          INTENT(IN)    :: MIXTE
      DOUBLE PRECISION, INTENT(IN)    :: MPART,DT,HMIN

      INTEGER, INTENT(IN)             :: NPOIN3,ICQ,SETDEP
!
      DOUBLE PRECISION, INTENT(INOUT) :: HDEP(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: EPAINCO(NPOIN2)
!
      DOUBLE PRECISION, INTENT(IN)    :: CFDEP,GRAV,RHOS,RHO0
      DOUBLE PRECISION, INTENT(IN)    :: KSPRATIO,AC
!
      TYPE(BIEF_OBJ)  , INTENT(IN)    :: DMOY,CF
      TYPE(BIEF_OBJ)  , INTENT(INOUT) :: CREF,ZREF,RUGOF
!
      DOUBLE PRECISION, INTENT(IN)    :: WC(NPOIN3)


      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN3), UETCAR(NPOIN2)

      DOUBLE PRECISION, INTENT(IN)    :: KARMAN,PRANDTL,FICT

      LOGICAL, INTENT(IN) :: SEDCO, SEDNCO
      DOUBLE PRECISION, INTENT(INOUT) :: FLUERC(NPOIN2), FLUERNC(NPOIN2)
      INTEGER, INTENT(IN) :: NTRAC, ITRAC


      INTEGER :: IPOIN

!      -----COMPUTES THE EXPLICIT EROSION FLUX-----
!
      IF(SEDCO) THEN
!
        CALL ERODC(CONC,EPAI,FLUER,TOB%R,DENSI,
     &             MPART,DT,NPOIN2,NCOUCH,TOCE,
     &             HN%R,HMIN,MIXTE,EPAICO)
!
      ELSEIF(SEDNCO) THEN
!
        CALL ERODNC(CFDEP,WC,HDEP,FLUER,TOB,DT,
     &              NPOIN2,NPOIN3,KSPRATIO,AC,RHOS,RHO0,HN,
     &              GRAV,DMOY,CREF,ZREF,CF,ICQ,RUGOF,Z,UETCAR,
     &              SETDEP,EPAINCO,MIXTE,
     &              KARMAN,PRANDTL,FICT)
!
      ELSEIF(MIXTE) THEN
!
        CALL ERODC(CONC,EPAI,FLUERC,TOB%R,DENSI,
     &             MPART,DT,NPOIN2,NCOUCH,TOCE,
     &             HN%R,HMIN,MIXTE,EPAICO)
!
        CALL ERODNC(CFDEP,WC,HDEP,FLUERNC,TOB,DT,
     &              NPOIN2,NPOIN3,KSPRATIO,AC,RHOS,RHO0,HN,
     &              GRAV,DMOY,CREF,ZREF,CF,ICQ,RUGOF,Z,UETCAR,
     &              SETDEP,EPAINCO,MIXTE,
     &              KARMAN,PRANDTL,FICT)
!
        DO IPOIN=1,NPOIN2
          FLUER(IPOIN) = FLUERNC(IPOIN) + FLUERC(IPOIN)
        ENDDO
!
      ENDIF

      RETURN
      END
