      SUBROUTINE SEDI3D_INIT(
     &    IVIDE,EPAI,TREST,CONC,TEMP,HDEP,
     &    ZR,ZF,X,Y,NPOIN2,NPOIN3,NPF,
     &    NCOUCH,TASSE,ITASS, RHOS,XKV,CFDEP,
     &    ESOMT, TOCE, SEDCO,CONC_LAYER,
     &    TOCE_LAYER, ES_LAYER, SEDNCO, MIXTE,
     &    EPAICO, EPAINCO, PVSCO, PVSNCO,
     &    PVSNCO0,H,Z,NPLAN,
     &    T2_05,
     &                T3DSUS_LU,T3DSUS_FMT,
     &                PRIVE,
     &    T3DGEO_LU,T3DGEO_FMT,
     &                 LAYTOCE,MESH2D,LISTIN,
     &    DEBUG, T3DSUS_NAME, READ_TOCE, D50, DMOY)

      USE BIEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      ! CONDIS
      INTEGER, INTENT(IN)             :: NPOIN2,NPOIN3,NCOUCH
      DOUBLE PRECISION, INTENT(OUT)   :: IVIDE(NPOIN2,NCOUCH+1), CFDEP
      DOUBLE PRECISION, INTENT(INOUT) :: EPAI(NPOIN2,NCOUCH)
      DOUBLE PRECISION, INTENT(INOUT) :: EPAICO(NPOIN2), EPAINCO(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: PVSCO(NPOIN2), PVSNCO(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: CONC(NPOIN2,NCOUCH)
      DOUBLE PRECISION, INTENT(INOUT) :: TEMP(NCOUCH,NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: HDEP(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: ZR(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: ZF(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2),Y(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TREST(NCOUCH)
      DOUBLE PRECISION, INTENT(INOUT) :: TOCE(NPOIN2,NCOUCH)
      DOUBLE PRECISION, INTENT(IN)    :: CONC_LAYER(NCOUCH)
      DOUBLE PRECISION, INTENT(IN)    :: ES_LAYER(NCOUCH)
      DOUBLE PRECISION, INTENT(IN)    :: TOCE_LAYER(NCOUCH)
      INTEGER, INTENT(INOUT)          :: NPF(NPOIN2)
      TYPE(BIEF_OBJ), INTENT (INOUT)  :: ESOMT
      LOGICAL, INTENT(IN)             :: TASSE
      LOGICAL, INTENT(IN)             :: SEDCO, SEDNCO, MIXTE
      INTEGER, INTENT(IN)             :: ITASS
      DOUBLE PRECISION, INTENT(IN)    :: RHOS,XKV, PVSNCO0
      TYPE(BIEF_OBJ), INTENT (INOUT)  :: H
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN3)
      INTEGER, INTENT(IN)             :: NPLAN
      ! SUISED
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: T2_05, PRIVE
      INTEGER, INTENT(IN)             :: T3DSUS_LU
      CHARACTER(LEN=8), INTENT(IN)  :: T3DSUS_FMT
      ! MUDSTRESS
      CHARACTER(LEN=8), INTENT(IN)  :: T3DGEO_FMT
      TYPE(BIEF_MESH), INTENT(IN)   :: MESH2D
      TYPE(BIEF_OBJ), INTENT(INOUT) :: LAYTOCE
      INTEGER, INTENT(IN)           :: T3DGEO_LU
      LOGICAL, INTENT(IN)           :: LISTIN
      ! ADDITIONAL INPUTS
      INTEGER, INTENT(IN) :: DEBUG
      CHARACTER(LEN=*) :: T3DSUS_NAME
      LOGICAL :: READ_TOCE
      DOUBLE PRECISION :: D50
      TYPE(BIEF_OBJ) :: DMOY

!###>TBE/CV MODIFICATION:
!    THE CALL TO CONDIS SHOULD ALWAYS BE DONE FIRST
!    VALUES THEN MAY BE MODIFIED FROM SEDIMENTOLOGICAL 2D RESULT
!
!        IF(T3DSUS)%NAME(1:1).EQ.' ') THEN
!GA: CONDIS HAS BEEN MODIFIED TO ALLOW TWO SEDIMENT CLASSES
          IF(DEBUG.GT.0) WRITE(LU,*) 'APPEL DE CONDIS'
          CALL CONDIS(IVIDE,EPAI,TREST,CONC,TEMP,HDEP,
     &                ZR,ZF,X,Y,NPOIN2,NPOIN3,NPF,
     &                NCOUCH,TASSE,ITASS, RHOS,XKV,CFDEP,
     &                ESOMT, TOCE, SEDCO,CONC_LAYER,
     &                TOCE_LAYER, ES_LAYER, SEDNCO, MIXTE,
     &                EPAICO, EPAINCO, PVSCO, PVSNCO,
     &                PVSNCO0,H,Z,NPLAN)
!
          IF(DEBUG.GT.0) WRITE(LU,*) 'RETOUR DE CONDIS'
!
!        ELSE
!
        IF(T3DSUS_NAME(1:1).NE.' ') THEN
!
! IMPORTANT NOTE: SUISED NOW READS A 2D FILE PREVIOUS SEDIMENTOLOGICAL
!                 FILE
!
          CALL SUISED(EPAI,HDEP,CONC,ZR,ZF,T2_05,
     &                NPOIN2,NCOUCH,ITASS,
     &                T3DSUS_LU,T3DSUS_FMT,
     &                PRIVE)
!
        ENDIF
!###<TBE/CV - END OF MODIFICATION
!
! LOOK FOR CRITICAL SHEAR STRESS FOR EROSION IN GEOMETRY FILE
        IF (READ_TOCE) THEN
          IF(DEBUG.GT.0) WRITE(LU,*) 'APPEL DE MUDSTRESS3D'
          CALL MUDSTRESS3D(T3DGEO_LU,T3DGEO_FMT,
     &                 LAYTOCE,NCOUCH,MESH2D,LISTIN)
          IF(DEBUG.GT.0) WRITE(LU,*) 'RETOUR DE MUDSTRESS3D'
        ENDIF
!
!       SO FAR CONSTANT MEAN DIAMETER=D50
        CALL OS('X=C     ',X=DMOY,C=D50)

      END SUBROUTINE
