      SUBROUTINE SEDI3D_BOTTOM_TREATMENT(
     &        IVIDE,EPAI,CONC,TREST,TEMP,HDEP,
     &        FLUDP,FLUDPT,FLUER,ZF,TA,
     &        WC,T3_01,T3_02,T3_03,NPOIN2,NPOIN3,NPFMAX,
     &        NCOUCH,NPF,LT,DT,DTC,GRAV,RHOS,CFMAX,TASSE,ITASS,
     &        ZF_S,ESOMT,VOLU2D,MASDEP,SETDEP,ZR,
     &        TS,FLUDPTC,FLUDPTNC,
     &        FLUERC,FLUERNC,MIXTE,FLUDPC,
     &        FLUDPNC,PVSCO,PVSNCO,CFDEP,
     &        EPAICO,EPAINCO,IPBOT,OPTBAN,NPLAN,
     &        DEBUG,SEDCO,SEDNCO)
      USE BIEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE

      INTEGER, INTENT(IN) ::  LT,NPOIN2,NPOIN3
      INTEGER, INTENT(IN) ::  NCOUCH,NPFMAX
!
      DOUBLE PRECISION, INTENT(INOUT) :: IVIDE(NPOIN2,NCOUCH+1)
      DOUBLE PRECISION, INTENT(INOUT) :: TREST(NCOUCH)
      DOUBLE PRECISION, INTENT(INOUT) :: TEMP(NCOUCH,NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: HDEP(NPOIN2)
!
      DOUBLE PRECISION, INTENT(INOUT) :: EPAI(NPOIN2,NCOUCH)
      DOUBLE PRECISION, INTENT(INOUT) :: EPAICO(NPOIN2), EPAINCO(NPOIN2)
!
      DOUBLE PRECISION, INTENT(IN)    :: CONC(NPOIN2,NCOUCH),ZR(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: ZF(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: TA(NPOIN3),WC(NPOIN3)
      DOUBLE PRECISION, INTENT(IN)    :: TS(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: T3_01(NPFMAX,6)
      DOUBLE PRECISION, INTENT(INOUT) :: T3_02(NPFMAX),T3_03(NPFMAX)
      DOUBLE PRECISION, INTENT(IN)    :: FLUDPT(NPOIN2),FLUER(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: FLUDPTC(NPOIN2),FLUERC(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: FLUDPTNC(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: FLUERNC(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: FLUDP(NPOIN2),ZF_S(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: FLUDPC(NPOIN2), FLUDPNC(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: PVSCO(NPOIN2), PVSNCO(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: ESOMT(NPOIN2)
!
      DOUBLE PRECISION, INTENT(IN)    :: DT,RHOS,GRAV,DTC, CFDEP
      DOUBLE PRECISION, INTENT(INOUT) :: CFMAX,MASDEP
!
      INTEGER, INTENT(INOUT) ::  NPF(NPOIN2)
!
      LOGICAL, INTENT(IN) :: TASSE, MIXTE
      INTEGER, INTENT(IN) :: SETDEP
      INTEGER, INTENT(IN) :: ITASS
!
      TYPE(BIEF_OBJ), INTENT(IN) :: VOLU2D
      TYPE(BIEF_OBJ), INTENT(IN) :: IPBOT
      INTEGER, INTENT(IN) :: OPTBAN
      INTEGER, INTENT(IN) :: NPLAN
      ! ADDITIONAL ARGUMENTS
      INTEGER, INTENT(IN) :: DEBUG
      LOGICAL, INTENT(IN) :: SEDCO, SEDNCO

!       FONVAS DOES ZF=ZR+HDEP, THUS HDEP MUST INCLUDE BEDLOAD
!       EROSION, HAS BEEN TAKEN INTO ACCOUNT INTO CLSEDI ABOVE
!   GA: FONVAS HAS BEEN MODIFIED TO ALLOW TWO SEDIMENT CLASSES
        IF (MIXTE) THEN
          IF(DEBUG.GT.0) WRITE(LU,*) 'APPEL DE FONVAS MIXTE'
          CALL FONVAS
     &       (IVIDE,EPAI,CONC,TREST,TEMP,HDEP,
     &        FLUDP,FLUDPT,FLUER,ZF,TA,
     &        WC,T3_01,T3_02,T3_03,NPOIN2,NPOIN3,NPFMAX,
     &        NCOUCH,NPF,LT,DT,DTC,GRAV,RHOS,CFMAX,TASSE,ITASS,
     &        ZF_S,ESOMT,VOLU2D,MASDEP,SETDEP,ZR,
     &        TS,FLUDPTC,FLUDPTNC,
     &        FLUERC,FLUERNC,MIXTE,FLUDPC,
     &        FLUDPNC,PVSCO,PVSNCO,CFDEP,
     &        EPAICO,EPAINCO,IPBOT,OPTBAN,NPLAN)

          IF(DEBUG.GT.0) WRITE(LU,*) 'RETOUR DE FONVAS MIXTE'
!
        ELSEIF (SEDCO.OR.SEDNCO) THEN

          IF(DEBUG.GT.0) WRITE(LU,*) 'APPEL DE FONVAS '
          CALL FONVAS
     &       (IVIDE,EPAI,CONC,TREST,TEMP,HDEP,
     &        FLUDP,FLUDPT,FLUER,ZF,TA,
     &        WC,T3_01,T3_02,T3_03,NPOIN2,NPOIN3,NPFMAX,
     &        NCOUCH,NPF,LT,DT,DTC,GRAV,RHOS,CFMAX,TASSE,ITASS,
     &        ZF_S,ESOMT,VOLU2D,MASDEP,SETDEP,ZR,
     &        TA,FLUDPTC,FLUDPTNC,
     &        FLUERC,FLUERNC,MIXTE,FLUDPC,
     &        FLUDPNC,PVSCO,PVSNCO,CFDEP,
     &        EPAICO,EPAINCO,IPBOT,OPTBAN,NPLAN)

          IF(DEBUG.GT.0) WRITE(LU,*) 'RETOUR DE FONVAS '
        ELSE
!
            WRITE(LU,*) ' '
          IF(LNG.EQ.1) THEN
            WRITE(LU,*) 'SEDI3D : ERREUR DE MOT CLE SEDIMENT'
          ENDIF
          IF(LNG.EQ.2) THEN
            WRITE(LU,*) 'SEDI3D : ERROR ON SEDIMENT KEY WORD'
          ENDIF
          CALL PLANTE(1)
          STOP
        ENDIF

      END SUBROUTINE

