!                    ***************
                     SUBROUTINE SEDI3D_Z
!                    ***************
!
     &(MASSUSP,MASSE,MASSUSP0,MASBED,MASBED0, MASDEP, WCHU,
     & TA_SEDI,EPAI,HDEP,CONC,FLUER,FLUDP,T2_01,NELEM2,NPOIN2,
     & NPOIN3,NPFMAX,NCOUCH,NPF,AT,TASSE,GIBSON,RHOS,VOLU2D,
     & CFDEP, EPAICO, EPAINCO, MIXTE,INFOGR,LT,NTRAC,DEBUG)
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
      USE BIEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
!
!+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
!
      INTEGER, INTENT(IN) :: NPFMAX,NCOUCH,NELEM2,NPOIN2,NPOIN3
      INTEGER, INTENT(IN) :: NPF(NPOIN2),NTRAC
!
      DOUBLE PRECISION, INTENT(INOUT) :: MASBED,MASDEP
      DOUBLE PRECISION, INTENT(IN) :: TA_SEDI(NPOIN3),VOLU2D(NPOIN2)
! BUG FIX TOM
      DOUBLE PRECISION, INTENT(IN) :: EPAI(NPOIN2,NCOUCH)
      DOUBLE PRECISION, INTENT(IN) :: EPAICO(NPOIN2), EPAINCO(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: HDEP(NPOIN2),FLUER(NPOIN2)
! BUG FIX T
      DOUBLE PRECISION, INTENT(IN) :: FLUDP(NPOIN2),CONC(NPOIN2,NCOUCH)
!
!
      DOUBLE PRECISION, INTENT(IN)    :: AT,RHOS,CFDEP
      DOUBLE PRECISION, INTENT(IN)    :: MASBED0
!
      LOGICAL, INTENT(IN)             :: TASSE,GIBSON,MIXTE
      DOUBLE PRECISION, INTENT(INOUT) :: MASSUSP,MASSUSP0,MASSE(*)
      TYPE(BIEF_OBJ), INTENT(INOUT) :: WCHU,T2_01
      LOGICAL, INTENT(IN) :: INFOGR
      INTEGER, INTENT(IN) :: LT,DEBUG
!
!+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
!
!         DETERMINE MASSUSP: MASS IN SUSPENSION
!         MASBED: MASS OF SEDIMENT BED
!         MASDEP: DEPOSITED MASS
          MASSUSP = MASSE(5+NTRAC)
!         INITIALISATION
          IF(LT.EQ.1) MASSUSP0 = MASSUSP
!
!GA: SED3D HAS BEEN MODIFIED TO ALLOW TWO SEDIMENT CLASSES
          IF(INFOGR) THEN
            IF(DEBUG.GT.0) WRITE(LU,*) 'APPEL DE SED3D'
            CALL SED3D(MASBED,MASBED0, MASDEP, WCHU,
     &                 TA_SEDI,
     &                 EPAI,HDEP,CONC,FLUER,FLUDP,T2_01,
     &                 NELEM2,NPOIN2,NPOIN3,NPFMAX,NCOUCH,
     &                 NPF,AT,TASSE,GIBSON,RHOS,VOLU2D,
     &                 CFDEP, EPAICO, EPAINCO, MIXTE)
!
            IF(DEBUG.GT.0) WRITE(LU,*) 'RETOUR DE SED3D'
          ENDIF
!
      RETURN
      END
